### ISSUE TITLE
pre-commit usage error syntax error

### ISSUE THREAD

**Issue by jjoocceeee** [talos-systems/conform#160]
I am trying to use Conform with pre-commit. When I install conform with pre-commit on my MAC, it works great, when I switch to a linux machine, I receive the following error: 
```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/go', 'get', './...')
return code: 2
expected return code: 0
stdout: (none)
stderr:
    # gonum.org/v1/gonum/lapack/gonum
    ../../../gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )
    # github.com/talos-systems/conform/internal/summarizer
    internal/summarizer/summarizer.go:101:24: undefined: strings.ReplaceAll
```

With this stack tract (using pre-commit):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/error_handler.py", line 56, in error_handler
    yield
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/main.py", line 372, in main
    args=args.rest[1:],
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/commands/hook_impl.py", line 187, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/commands/run.py", line 355, in run
    install_hook_envs(hooks, store)
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/repository.py", line 83, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/languages/golang.py", line 81, in install_environment
    cmd_output_b('go', 'get', './...', cwd=repo_src_dir, env=env)
  File "/usr/local/lib/python3.6/dist-packages/pre_commit/util.py", line 156, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/go', 'get', './...')
return code: 2
expected return code: 0
stdout: (none)
stderr:
    # gonum.org/v1/gonum/lapack/gonum
    ../../../gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )
    # github.com/talos-systems/conform/internal/summarizer
    internal/summarizer/summarizer.go:101:24: undefined: strings.ReplaceAll
```

Go version:  `go version go1.10.4 linux/amd64`
Operating System: `Ubuntu 18.04.4 LTS`

.conform:
```policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: false
        case: lower
        invalidLastCharacters: .
      dco: false
      gpg: false
      maximumOfOneCommit: true
      requireCommitBody: true
      conventional:
        types:
          - "type"
        scopes:
          - "scope"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        This is the contents of a license header.
```

.pre-commit-config.yaml:
```repos:
  - repo: https://github.com/talos-systems/conform
    rev: master
    hooks:
      - id: conform
        stages:
          - commit-msg
```

Because of this syntax error, I can't use conform when writting a commit message. Can you offer me any guidance or a work around? 

Thanks!

**Comment by andrewrynhard** [comment]
Looks like you need at least go 1.12 for `strings.ReplaceAll`.

**Comment by jjoocceeee** [comment]
That was it! Thank you!
